// SPDX-License-Identifier: MIT

/* 
*    ================================================================
*        This token contract was generated by using Pinky Finance  
*                    Webiste: https://pinky.finance
*    ================================================================
*/

pragma solidity ^0.8.17;

import "./BasicToken.sol";

contract MintableToken is BasicToken {

    constructor(string memory name_,
        string memory symbol_,
        uint8 decimals_,
        uint256 totalSupply_,
        address serviceFeeReceiver_,
        uint256 serviceFee_
    ) BasicToken(name_, symbol_, decimals_, totalSupply_, serviceFeeReceiver_, serviceFee_) payable { }

    function mint(uint256 value) external {
        _mint(msg.sender, value);
    }
}
